export const createPlayer = (overrides = {}) => ({
  id: overrides.id ?? 'player-1',
  name: overrides.name ?? 'Ari',
  avatar: overrides.avatar ?? 'fox',
  profileId: overrides.profileId ?? 'none',
  cityId: overrides.cityId ?? 'suburbia',
  educationTrackId: overrides.educationTrackId ?? 'self-taught',
  jobId: overrides.jobId ?? 'content-creator',
  careerTrack: overrides.careerTrack ?? null,
  cash: overrides.cash ?? 3840,
  debt: overrides.debt ?? 5280,
  assetsValue: overrides.assetsValue ?? 2880,
  netWorth: overrides.netWorth ?? 1440,
  monthlyIncome: overrides.monthlyIncome ?? 4800,
  physicalHealth: overrides.physicalHealth ?? 70,
  mentalHealth: overrides.mentalHealth ?? 70,
  stress: overrides.stress ?? 31,
  playerTraits: overrides.playerTraits ?? { grit: 0, focus: 0, resilience: 0, riskTolerance: 0 },
  statusEffects: overrides.statusEffects ?? [],
  actionHistory: overrides.actionHistory ?? [],
  activeIssues: overrides.activeIssues ?? [],
  pendingConsequences: overrides.pendingConsequences ?? [],
  progressionArcs:
    overrides.progressionArcs ?? [
      { id: 'burnout', label: 'Burnout', value: 0, band: 'calm', headline: 'You are keeping up with life.' },
      { id: 'recovery', label: 'Recovery', value: 0, band: 'steady', headline: 'You are holding your ground.' },
      { id: 'careerMomentum', label: 'Career Momentum', value: 0, band: 'steady', headline: 'Your career is moving at a steady pace.' },
    ],
  ...overrides,
})

export const createGame = (overrides = {}) => ({
  id: overrides.id ?? 'game-1',
  name: overrides.name ?? 'Family Game Night',
  status: overrides.status ?? 'active',
  players: overrides.players ?? [createPlayer()],
  turnNumber: overrides.turnNumber ?? 1,
  activePlayerIndex: overrides.activePlayerIndex ?? 0,
  moveHistory: overrides.moveHistory ?? [],
  lastUpdated: overrides.lastUpdated ?? Date.now(),
  createdAt: overrides.createdAt ?? Date.now(),
  resumable: overrides.resumable ?? true,
  ...overrides,
})
